branches:
    only:
        - master

sudo: required
dist: trusty

services:
    - cassandra
    - memcached
    - redis

language: python
python:
    - "2.7"
    - "3.4"

virtualenv:
    system_site_packages: true

before_install:
    - sudo add-apt-repository -y ppa:reddit/ppa
    - sudo apt-get update -q
    - sudo apt-get install -y python python3 fbthrift-compiler make pylint python-flake8 python3-cassandra python3-coverage python3-cqlmapper python3-fbthrift python3-gevent python3-nose python3-posix-ipc python3-pymemcache python3-redis python3-requests python3-setuptools python3-sqlalchemy python3-webtest python-coverage python-cqlmapper python-fbthrift python-gevent python-nose python-posix-ipc python-pymemcache python-pyramid python-redis python-requests python-setuptools python-sqlalchemy python-webtest python-alabaster python-sphinx python-sphinxcontrib.spelling python-enum34 python-mock

script:
    - make
    - nosetests -v
    - sphinx-build -M doctest docs/ build/
    - sphinx-build -M spelling docs/ build/
    - make lint
